apiVersion: apps/v1
kind: Deployment
metadata:
  name: issuance-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: issuance
  template:
    metadata:
      labels:
        app: issuance
    spec:
      containers:
        - name: issuance
          image: issuance-service
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
